# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/reproduce-work',
                'doc_host': 'https://reproduce-work.github.io',
                'git_url': 'https://github.com/reproduce-work/reproduce-work',
                'lib_path': 'reproduce_work'},
  'syms': {'reproduce_work.core': {'reproduce_work.core.save': ('dynamic.html#save', 'reproduce_work/core.py')}}}
