# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/reproduce-work',
                'doc_host': 'https://reproduce-work.github.io',
                'git_url': 'https://github.com/reproduce-work/reproduce-work',
                'lib_path': 'reproduce_work'},
  'syms': { 'reproduce_work.build': { 'reproduce_work.build.main': ('build.html#main', 'reproduce_work/build.py'),
                                      'reproduce_work.build.read_base_config': ('build.html#read_base_config', 'reproduce_work/build.py'),
                                      'reproduce_work.build.replace_inserts_with_toml_data': ( 'build.html#replace_inserts_with_toml_data',
                                                                                               'reproduce_work/build.py')},
            'reproduce_work.core': { 'reproduce_work.core.generate_config': ('core.html#generate_config', 'reproduce_work/core.py'),
                                     'reproduce_work.core.read_base_config': ('core.html#read_base_config', 'reproduce_work/core.py'),
                                     'reproduce_work.core.test_validate_base_config': ( 'core.html#test_validate_base_config',
                                                                                        'reproduce_work/core.py'),
                                     'reproduce_work.core.validate_base_config': ( 'core.html#validate_base_config',
                                                                                   'reproduce_work/core.py')},
            'reproduce_work.dynamic': {'reproduce_work.dynamic.save': ('dynamic.html#save', 'reproduce_work/dynamic.py')}}}
