[project]
full_title = "\\texttt{reproduce.work}: A framework to facilitate cross-platform computational reproducibility in scientific publishing"
abstract = """
In metascience, computational reproduction is the process of reproducing the results of a scientific paper
using the data and code provided by the authors of the paper. This subject sits within the broader context of 
``reproducibility" in scientific  research, which has been core to the philosophy of science for decades. However, 
the practice of science has fallen woefully short of meeting even basic standards toward true and widespread 
reproducibility. In this project, we focus primarily on addressing the narrow problem of computational reproducibility. 
We propose a framework for facilitating computational reproducibility in scientific publishing, which we call 
reproduce.work. The reproducibility standards are designed to be cross-platform and to work with any programming language, 
though our first working software interfaces are in Python.
We highlight the distinction between open and reproducibile practices and show how our software framework encourages 
both simultaneously. The results of this very paper can be reproduced on any machine that can execute a containerized 
image using the reproduce.work workflow. We conclude by discussing the potential of the framework for improving rigor 
and fidelity of computational science for both producers and consumers of published work.
"""
github_repo = "reproduce-work/reproduce-work"
base_url = "https://github.com/reproduce-work/reproduce-work"

[repro]
version = "reproduce.work/v1/default"
stages = [ "init", "develop", "build",]
verbose = true
document_dir = "document"
notebooks = [ "nbs/00_introduction.ipynb", "nbs/01_core.ipynb", "nbs/03_paper.ipynb",]

[repro.files]
input = "document/main.md"
dynamic = "reproduce/pubdata.toml"
latex_template = "document/latex/template.tex"
bibfile = "document/latex/bibliography.bib"
output_linefile = "document/latex/report.tex"
output_report = "document/report.pdf"
watch = [ "document/main.md", "reproduce/pubdata.toml", "document/latex/template.tex", "document/latex/bibliography.bib", "nbs/00_introduction.ipynb", "img/reproducible_plot.svg", "nbs/01_core.ipynb", "nbs/03_paper.ipynb", "img/scatter_plot.pdf",]

[authors.author1]
email = "alex.miller@marshall.usc.edu"
name = "Alex P. Miller"
affiliation = "USC Marshall School of Business"

[repro.stage.init]
script = """
docker build -t reproduce-work-dev .
docker build -t tex-prepare https://github.com/reproduce-work/tex-prepare.git
docker build -t tex-compile https://github.com/reproduce-work/tex-compile.git
docker build -t watcher https://github.com/reproduce-work/rwatch.git
"""

[repro.stage.develop]
script = """
docker run -v $(pwd):/home/jovyan -p 8888:8888 reproduce-work-dev
docker run watcher "document/main.md,reproduce/pubdata.toml,document/latex/template.tex,document/latex/bibliography.bib,nbs/00_introduction.ipynb,img/reproducible_plot.svg,nbs/01_core.ipynb,nbs/03_paper.ipynb,img/scatter_plot.pdf" "echo "File has changed!" && build_cmd"
"""

[repro.stage.build]
script = """
docker run --rm -i -v $(pwd):/home/jovyan -p 8888:8888 reproduce-work-dev python reproduce_work.build() # this replaces instances of INSERTvar in input file
docker run --rm -i -v $(pwd):/home -e REPROWORKDIR="reproduce" -e REPROWORKOUTFILE="document/report.pdf" tex-prepare python build.py # this converts the markdown to latex
docker run --rm -i --net=none -v $(pwd):/home tex-compile sh -c "cd /home/reproduce/tmp/document/latex && xelatex compiled.tex" # this compiles the latex
"""
