version: '3'

services:
  reproduce-watcher:
    image: watcher
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${PWD}:/usr/src/app
    environment:
      - REPROWORKDIR=reproduce
      - REPROWORKOUTFILE=reproduce/latex/compiled.tex
      - HOSTWORKDIR=${PWD}
    command:
      - "reproduce/main.md,reproduce/config.toml,reproduce/pubdata.toml,reproduce/latex/template.tex,nbs/*.ipynb"
      - "docker run --rm -i -v ${HOSTWORKDIR}:/home/jovyan -p 8878:8888 reproduceworkdev nbdev_export && docker-compose -f reproduce/docker-compose-reproduce.yml up tex-prepare && docker-compose -f reproduce/docker-compose-reproduce.yml up tex-compile"

    stdin_open: true
    tty: true

  tex-prepare:
    image: tex-prepare
    volumes:
      - ${HOSTWORKDIR}:/home
    environment:
      - REPROWORKDIR=reproduce
      - REPROWORKOUTFILE=reproduce/latex/compiled.tex
    #command: ls -al /home
    command: python /run.py

  tex-compile:
    image: tex-compile
    volumes:
      - ${HOSTWORKDIR}:/home
    network_mode: "none"
    environment:
      - REPROWORKDIR=reproduce
      - REPROWORKOUTFILE=reproduce/latex/compiled.tex
    command:
      - sh
      - -c
      - cd /home/reproduce/latex && lualatex compiled.tex

#export HOSTWORKDIR="$(pwd)" && docker compose -p reproducework -f "reproduce/docker-compose-reproduce.yml" up --build
#export HOSTWORKDIR="$(pwd)" && docker run --rm -i -v ${HOSTWORKDIR}:/home/jovyan -p 8881:8888 reproduceworkdev nbdev_export
#"export HOSTWORKDIR=\"$(pwd)\" && docker run --rm -i -v ${HOSTWORKDIR}:/home/jovyan -p 3000 reproduceworkdev livepreview && docker-compose -f reproduce/docker-compose-reproduce.yml up tex-prepare && docker-compose -f reproduce/docker-compose-reproduce.yml up tex-compile"
