[x]
description = "x-values for scatter plot"
published_url = "https://github.com/reproduce-work/reproduce-work/blob/main/reproduce/pubdata.toml#L1-L10"
generating_script = "https://github.com/reproduce-work/reproduce-work/blob/main/nbs/03_paper.ipynb"
type = "data"
timestamp = "2023-12-12T23:24:45.721297"
content_hash = "1da264418b3aabfb16c81c7f0940442c"
timed_hash = "a93de6dd2c9f00a508787e0cdb823b53"
python_version = "3.9.13 | packaged by conda-forge | (main, May 27 2022, 17:23:23)  [GCC 10.3.0]"
platform_info = "Linux-6.5.13-orbstack-00115-g011f8a6f3e5f-aarch64-with-glibc2.35"

[y]
description = "y-values for scatter plot"
published_url = "https://github.com/reproduce-work/reproduce-work/blob/main/reproduce/pubdata.toml#L12-L21"
generating_script = "https://github.com/reproduce-work/reproduce-work/blob/main/nbs/03_paper.ipynb"
type = "data"
timestamp = "2023-12-12T23:24:53.316327"
content_hash = "a57e05b83ead3116119cda28d905fa92"
timed_hash = "57a4e66e9ee2302ec5eb23681d134a9b"
python_version = "3.9.13 | packaged by conda-forge | (main, May 27 2022, 17:23:23)  [GCC 10.3.0]"
platform_info = "Linux-6.5.13-orbstack-00115-g011f8a6f3e5f-aarch64-with-glibc2.35"

[scatter_plot_1749877b]
plot = true
description = "Scatter plot with OLS model line from regression of y on x"
badge = "reproduce-work-logo"
plot_data = "{'x': 'https://github.com/reproduce-work/reproduce-work/blob/main/reproduce/pubdata.toml#L1-L10', 'y': 'https://github.com/reproduce-work/reproduce-work/blob/main/reproduce/pubdata.toml#L1-L10', 'alpha': '2.136814322490183', 'beta': '0.2921029690635062', 'p_alpha': '1.4742605344903455e-83', 'p_beta': '0.003632109212982725'}"
type = "file"
filepath = "img/scatter_plot.pdf"
timestamp = "2023-12-12T23:25:04.793767"
python_version = "3.9.13 | packaged by conda-forge | (main, May 27 2022, 17:23:23)  [GCC 10.3.0]"
platform_info = "Linux-6.5.13-orbstack-00115-g011f8a6f3e5f-aarch64-with-glibc2.35"
content_hash = "a3cfaf9534e722221e868f1668b6f47f"
timed_hash = "90beb67059659b59aa065f7747160aff"
published_url = "https://github.com/reproduce-work/reproduce-work/blob/main/reproduce/pubdata.toml#L23-L37"
content_url = "https://github.com/reproduce-work/reproduce-work/blob/main/img/scatter_plot.pdf"
generating_script = "https://github.com/reproduce-work/reproduce-work/blob/main/nbs/03_paper.ipynb"

[ols_model_summary]
description = "OLS Model Summary from regression of y on x"
badge = "reproduce-work-logo"
model_data = "{'x': 'https://github.com/reproduce-work/reproduce-work/blob/main/reproduce/pubdata.toml#L1-L10', 'y': 'https://github.com/reproduce-work/reproduce-work/blob/main/reproduce/pubdata.toml#L12-L21'}"
plots = [ "https://github.com/reproduce-work/reproduce-work/blob/main/reproduce/pubdata.toml#L23-L37",]
published_url = "https://github.com/reproduce-work/reproduce-work/blob/main/reproduce/pubdata.toml#L39-L51"
generating_script = "https://github.com/reproduce-work/reproduce-work/blob/main/nbs/03_paper.ipynb"
type = "data"
timestamp = "2023-12-12T23:25:46.550445"
content_hash = "d8f1208292c669322492ed62550c77dd"
timed_hash = "b4dc4a36ccfd82aa8e43052f4ed98ca7"
python_version = "3.9.13 | packaged by conda-forge | (main, May 27 2022, 17:23:23)  [GCC 10.3.0]"
platform_info = "Linux-6.5.13-orbstack-00115-g011f8a6f3e5f-aarch64-with-glibc2.35"