# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/hteml',
                'doc_host': 'https://alexmill.github.io',
                'git_url': 'https://github.com/alexmill/hteml',
                'lib_path': 'hteml'},
  'syms': {'hteml.core': {'hteml.core.foo': ('core.html#foo', 'hteml/core.py')}}}
